# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Reaction

# Model Form Field configuration
form: $/appchat/chat/models/reaction/fields.yaml

# Model Class name
modelClass: AppChat\Chat\Models\Reaction

# Default redirect location
defaultRedirect: appchat/chat/reactions

# Create page
create:
    title: backend::lang.form.create_title
    redirect: appchat/chat/reactions/update/:id
    redirectClose: appchat/chat/reactions

# Update page
update:
    title: backend::lang.form.update_title
    redirect: appchat/chat/reactions
    redirectClose: appchat/chat/reactions

# Preview page
preview:
    title: backend::lang.form.preview_title
